services:
  app:
    build:
      context: ../..                      # <- racine du projet
      dockerfile: docker/plant-disease-detection_docker/Dockerfile
    container_name: plant_disease_detection_app
    volumes:
      - ../..:/app                        # <- on monte tout le projet dans /app
    working_dir: /app
    command: python app_V2.py
    ports:
      - "5000:5000"
